### ISSUE TITLE
Add python3 support

### ISSUE THREAD

**Issue by Daniel-at-github** [iogf/sukhoi#3]
Now that the repo is [trendy](https://github.com/trending/python?since=monthly) it is a good time to [make it compatible with pyton3](http://python-future.org/compatible_idioms.html) (or convert to it with 2to3).
Checking with [travis](https://docs.travis-ci.com/user/getting-started/) in every commit [for python3](https://docs.travis-ci.com/user/getting-started/) will make easier to stay compatible (one test is better than nothing).

**Comment by iogf** [comment]
Yes, i have finally ported untwisted to py3, i'm going to do it tomorrow.

**Comment by gramster** [comment]
Any ETA? Sorry to be a pest but I'm giving a Python talk in Python 3 in a week and would like to include this as one of my examples.

**Comment by iogf** [comment]
I have had some issues with time, having to get things done in other context. i'll be porting it to python3 tomorrow.

**Comment by iogf** [comment]
I have finally ported to python3. I have dropped py2 support.
