### ISSUE TITLE
Error: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by gramster** [iogf/sukhoi#5]
I just get this error when I try use the library with Python 3.5.

Simple repo:

    from sukhoi import MinerLXML, core

    class MyMiner(MinerLXML):
        def run(self, dom):
            pass
        
    MyMiner('http://google.com')

**Comment by iogf** [comment]
You should make sure to have the versions in requirements.txt file installed for python3.

Make sure you have all these versions installed for python3.


untwisted==1.4.1
websnake==1.3.0
ehp==2.0.0
lxml
bs4

post here your output for 

~~~
pip  freeze
~~~

**Comment by iogf** [comment]
You need to reinstall sukohi, the latest version, the one that runs on python3.
It is 1.0.0 , this one wouldnt run on python2, i have dropped python2 support. Just py3 now.

**Comment by iogf** [comment]
Make sure you have installed the dependencies using python3 instead of python2 too.

**Comment by iogf** [comment]
Try installing runniing this:

~~~
pip install -r requeriments.txt --no-cache
pip install sukhoi --no-cache
~~~

Then test it.

**Comment by gramster** [comment]
My versions are below. 

untwisted==1.4.1
ehp==2.0.0
sukhoi==1.0.0
websnake==1.3.0
lxml==3.8.0
bs4==0.0.1

If I switch to MinerEHP I still get the problem.

**Comment by iogf** [comment]
interesting, it seems your versions are correct.
It runs correctly here.

which is your default python? is it python2 or python3? which is the output of

python --version ?

and pip --version ?

**Comment by gramster** [comment]
Ah, something is messed up in my environment. I created a clean environment and the problem went away. Sorry for wasting your time.

**Comment by iogf** [comment]
No worries.
